import Link from 'next/link';

export const metadata = {
    title: 'Welcome to personal-log-app',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <h1>Personal log app</h1>
                <div>
                    <Link href="/">Log</Link>
                </div>
                <div>
                    <Link href="/log">Edit logs</Link>
                </div>
                <div>
                    <Link href="/analyze">Analyze</Link>
                </div>
                {children}
            </body>
        </html>
    );
}
